language: java
jdk:
  - openjdk8

branches:
  only:
    - yorer

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script:
  - "./gradlew clean build"

notifications:
  email:
    recipients:
      - jdaddyorer@gmail.com

